export default {
  NUMBER_CHANGED: 'NUMBER_CHANGED',
  SUBMITTED: 'SUBMITTED',
  ADDED: 'ADDED',
  SUBTRACTED: 'SUBTRACTED',
  MULTIPLIED: 'MULTIPLIED',
  DIVIDED: 'DIVIDED',
  CALCULATIONS_APPLIED: 'CALCULATIONS_APPLIED',
};
